export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const GET_BLOGBYID_SUCCESS = "GET_BLOGBYID_SUCCESS";
export const GET_BLOG_COUNT_SUCCESS = "GET_BLOG_COUNT_SUCCESS";

export const REMOVE_COMMENT_SUCCESS = "REMOVE_COMMENT_SUCCESS";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";

export const LOADING_UI = "LOADING_UI";
export const STOP_LOADING_UI = "STOP_LOADING_UI";

export const LOADING_BLOGS = "LOADING_BLOGS";

export const LOADING_COMMENTS = "LOADING_COMMENTS";
export const STOP_LOADING_COMMENTS = "STOP_LOADING_COMMENTS";

export const AUTHENTICATE = "AUTHENTICATE";
export const UNAUTHENTICATE = "UNAUTHENTICATE";

export const SET_ACTION_SUCCESS = "SET_ACTION_SUCCESS";
export const SET_ACTION_ERROR = "SET_ACTION_ERROR";
export const CLEAR_ACTION_RESULT = "CLEAR_ACTION_RESULT";
